name: Build Gradle 2.1
on:
  push:
    branches: [ "2.1" ]
  pull_request:
    branches: [ "2.1" ]
permissions:
  contents: read
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 Corretto
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: List files
      run: ls -al Projects/Core
    - name: Execute Gradle build
      run: ./gradlew build --info
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: output/**/*
